### PR TITLE
Add [Blogs and Portals]: Entity Systems Wiki

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
Why do you think the link is worth adding on this list?
Please describe the answer here

Does this project has any License?
Please describe the answer here

### CODE REVIEW

**Comment by OvermindDL1** [comment]
Eh, that 'wiki' has a lot of old information and styles, no lists of *any* modern ECS implementations, etc...  I think at this point it's defunct.

**Comment by OvermindDL1** [comment]
Some better examples:

Thus is using the Rust language (mostly, some C++), but it is a fantastic example of 'why' ECS's are "in general" superior for games, it's a talk (both the video and text cover the same material):  https://kyren.github.io/2018/09/14/rustconf-talk.html

Consequently, the Rust ECS library `specs` online website has some some of the best descriptions about 'what' and ECS library is (and how to use specs in Rust).

The C++ ECS library [entt](https://github.com/skypjack/entt) is the most performant and accurate ECS library in C++ by far (it and Rust's `specs` are about on par for speed and most features) while having a *LOT* of ECS information in it's [wiki](https://github.com/skypjack/entt/wiki).

**Comment by dzmitry-lahoda** [comment]
Give me several days to try to disagree after read all material.

**Comment by OvermindDL1** [comment]
> Give me several days to try to disagree after read all material.

Lol, all good.  ^.^

If that old http://entity-systems.wikidot.com/ wiki was *significantly* updated (and there has been a **LOT** of ECS development since it came out) then it would be useful, though the wikidot website itself being used is questionable at this point (so many odd ads!), so I'd opt for a better place, like an `awesome-ecs` github repo that also sets up it's own github wiki or so.

**Pull request closed without merging**
