### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Kavex**
Added Project Management and Game Jams links

### CODE REVIEW

**Comment by Kavex** [comment]
Looks like the Travis CI fail is other links

**Comment by Kavex** [comment]
Also lots of resources too https://game-development.zeef.com/david.arcila

**Comment by ellisonleao** [comment]
Cool @Kavex , thanks for the contribution. Don't worry about the CI for now, there are some false positives, i am still working on that CI script. Cheers!

About the zeef page, i used to have page over there but i decided to just keep this repo since they don't have a way of keeping both updated with the same content for now

**Comment by Kavex** [comment]
You are very welcome @ellisonleao I'll try to add more resources because I have a few I'm sure you don't have.  I agree with you on using a repo like this over zeef but I just wanted to point out that page because people have added quite a bit of resources you might like to add. I honesty haven't looked over it 100% because I used to use the old version that used google docs. 

Anyways cheers

**Comment by ellisonleao** [comment]
yeah i've checked that page a few time, but its kinda hard to keep on track with this one.

**Pull request merged**
