### PR TITLE
Travis Update 

### PR DESCRIPTION
**Pull request by ReadmeCritic**

### CODE REVIEW

**Comment by ellisonleao** [comment]
qici engine is not raising any errors here, why would it need to be whitelisted?

**Comment by ReadmeCritic** [comment]
503 here https://travis-ci.org/ellisonleao/magictools/builds/108039575

**Comment by ellisonleao** [comment]
i ran the build again and not its passing https://travis-ci.org/ellisonleao/magictools/builds/108039575

**Comment by ReadmeCritic** [comment]
cool!

**Pull request closed without merging**
