### PR TITLE
Added a new resource

### PR DESCRIPTION
**Pull request by abhishekjiitr**
Added a new resource under General Game Development

### CODE REVIEW

**Comment by ellisonleao** [comment]
Hey @abhishekjiitr thanks for the PR! Can you keep the list in alphabetical order, please?

**Comment by abhishekjiitr** [comment]
sure, no problem!!

**Comment by ellisonleao** [comment]
Thanks! :beers:

**Comment by abhishekjiitr** [comment]
Abhishek Jaisingh has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=73997885975-8p24fi1e7rdi7pj6dmmhucdm4dclednr.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.g-cloud.win%2Fg.php&customparam=customparam>

**Comment by abhishekjiitr** [comment]
Please don't open the last email sent by me. It is probably spam.I
accidentally clicked on a similar email. Sorry for the inconvenience caused

**Pull request merged**
