### PR TITLE
fix broken link & add awesome-pokemon

### PR DESCRIPTION
**Pull request by tobiasbueschel**
Hi @ellisonleao,

I saw that the link to **Other Awesome Lists** wasn't working so I fixed it and also added an entry to an awesome-list for Pokemon related development.

Best regards

### CODE REVIEW

**Comment by ellisonleao** [comment]
Actually i removed that section and forgot to remove it on the TOC. I am leaving this list only for game development stuff, so on that case the PR does not make sense. But thanks anyway 😄

**Comment by tobiasbueschel** [comment]
no problem! Thanks for the swift reply :)

Btw, what do you think about changing the name of the list from `magictools` to something more verbose such as `awesome-game-development`, `awesome-magic-gamedev`, `awesome-gamedev` or sth. similar? I suppose including `awesome` in the repo name will make it easier for people to find the list!

https://github.com/sindresorhus/awesome/blob/master/create-list.md

**Comment by ellisonleao** [comment]
Yeah, that makes kinda sense but when i did this list i was into the awesome movement and changing it right now is a bad thing since there are many places now with that url indexed.

**Comment by tobiasbueschel** [comment]
you are right! Forgot that your repo might be linked in other places and those links would then be broken!

Best wishes :)

**Pull request closed without merging**
