### PR TITLE
Major re-haul of the list 

### PR DESCRIPTION
**Pull request by Kavex**
If you like these changes you are more than welcome to merge them. I organized and renamed sections so it makes more logical sense. I also added an image to the top (I checked the license before hand) 

## Changes ##
------------

- Added Contributors to CONTRIBUTING.MD
- Reorganized, categorized, and alphabetized Graphics so it's easier to find things (omg so much better)
- Added price icons to Graphics
- Moved audio section under Graphics because it has assets to in case people are looking
- Renamed Collections under Audio to audio assets to stay consistent
- Renamed Music and Audio Editors under Audio to audio tools to stay consistent
- Moved Complete Game Sources under Code section (it is code duh!)
- Renamed Complete Game Sources to Game Source Code (better title, less confusion)
- Moved Ads to Code and renamed to Ads and Monetization because that is code for your project
- Added Media section for the some of the media that was in Must see
- Added Design and Management Section for Board games and Project Management
- Alphabetized category names in Learn
- Added image and resized it so it looked better

### CODE REVIEW

**Comment by ellisonleao** [comment]
Hey @Kavex thanks for the PR, i will take some time to exam it, so i ask a little patience on this one.

**Comment by Kavex** [comment]
@ellisonleao yeah no problem

Feel free to make use or not. I'm just trying to make my fork a little better is all.

**Comment by ellisonleao** [comment]
Apart from the contributors names on the CONTRIBUTING file, everything looks good. Can you please just make that little change?

**Comment by Kavex** [comment]
Thanks for your consideration on the merge but I'll have to decline that one.

I'll continue with my own fork, Thanks @ellisonleao

Closing Pull Request

**Pull request closed without merging**
