### PR TITLE
Added a section containing some of the most known Game Dev Communities

### PR DESCRIPTION
**Pull request by ZarakiKanzaki**
Why do you think the link is worth adding on this list?
As asked in issue #300 I included some of the most known game dev communities, some of them may contain many resources on YT that could hep newcomer devs to learn.

Does this project has any License?
No.

### CODE REVIEW

**Comment by ZarakiKanzaki** [comment]
@ellisonleao  do you think this pr can me merged?

**Review by ellisonleao — CHANGES_REQUESTED** [review]
can you move the section to "must-see" sub-section please?

**Comment by ZarakiKanzaki** [comment]
sure! no problem will do today 😊

**Comment by ZarakiKanzaki** [comment]
@ellisonleao  done the change, please if you have any further requests don't hesitate to ask 😊

**Pull request merged**
